export const products = [
  {
    id: 1,
    name: "Dreamy Bloom Tee",
    price: 499,
    badge: "New!",
    category: "Tees",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Straight out of your moodboard — soft petals, tulips & charm. A vibe that's pretty inside and out.",
    longDescription: "Each piece is hand-printed with love using fabric-safe inks. The Dreamy Bloom Tee features delicate floral motifs inspired by Pinterest boards and summer gardens. Light, breathable cotton that feels like a warm hug.",
    images: ["/images/Pinterest Flower Tee.jpg"],
    instagramUrl: "https://www.instagram.com/p/DMau7ngtELM/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 2,
    name: "Spider Star Tee",
    price: 599,
    badge: "Best Seller!",
    category: "Tees",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Bold white spider with red web & stars — made for the edgy, comic-inspired streetwear fan.",
    longDescription: "A statement piece for the bold and the brave. Hand-printed spider web design with star accents in striking red and white. Perfect for streetwear enthusiasts and comic lovers.",
    images: ["/images/Spider Web Tee.jpg"],
    instagramUrl: "https://www.instagram.com/p/DMdRlkbJbYR/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 3,
    name: "One Piece Luffy Tee",
    price: 699,
    badge: "Anime Drop!",
    category: "Anime",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Custom anime tee for Straw Hat fans. Available in both hand-painted & digital print options!",
    longDescription: "For the One Piece fans who never give up on their dreams. Luffy's iconic energy captured in vibrant hand-printed form. Available in hand-painted and digital print versions — specify your preference at checkout.",
    images: ["/images/Luffy Anime Tee.jpg"],
    instagramUrl: "https://www.instagram.com/p/DLzoc1RNxio/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 4,
    name: "Bulbasaur Chill Tee",
    price: 499,
    badge: "New Drop!",
    category: "Anime",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Chill like a Bulbasaur in the sun — perfect for Pokémon lovers who enjoy cozy style.",
    longDescription: "Front-print only. Bulbasaur lounging in golden sunlight — a peaceful, cozy design for Pokemon fans who appreciate the chill side of life. Soft cotton, relaxed fit.",
    images: ["/images/Bulbasaur.jpg"],
    instagramUrl: "https://www.instagram.com/p/DMstt1ztYg9/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    note: "Only front print",
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 5,
    name: "Golden Leo Vibes Tee",
    price: 599,
    badge: "New One!",
    category: "Zodiac",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Channel your inner lion with this stunning golden Leo design — perfect for Leo season and zodiac enthusiasts.",
    longDescription: "Regal, bold, and unmistakably Leo. This golden zodiac tee is hand-printed with a majestic lion design that celebrates Leo season all year round. For the fire signs who wear their identity proudly.",
    images: ["/images/leo.jpg"],
    instagramUrl: "https://www.instagram.com/p/DMstt1ztYg9/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 6,
    name: "Naruto Uzumaki Tee",
    price: 699,
    badge: "Anime Drop!",
    category: "Anime",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Believe it! Show your ninja way with this epic Naruto design — a must-have for Hidden Leaf fans.",
    longDescription: "Dattebayo! This hand-printed Naruto tee captures the spirit of the Hidden Leaf's most determined ninja. Bold, vivid, and full of chakra energy. A must-have for any Naruto fan's wardrobe.",
    images: ["/images/Naruto.jpg"],
    instagramUrl: "https://www.instagram.com/p/DP8_jbmCZ5a/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 7,
    name: "BT21 Cutie Tee",
    price: 599,
    badge: "New Drop!",
    category: "K-Pop",
    garmentType: "Short Sleeve Round Neck T-shirt",
    description: "Adorable BT21 characters bringing K-pop cuteness to your wardrobe — perfect for ARMY and BT21 fans!",
    longDescription: "For the ARMY who wear their love proudly. Adorable BT21 characters hand-printed with soft, pastel-friendly inks. Cute, cozy, and completely irresistible for any K-pop fan.",
    images: ["/images/BT21.jpg"],
    instagramUrl: "https://www.instagram.com/p/DQHSLrfjKVX/",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Hand wash cold. Do not bleach. Dry in shade."
  },
  {
    id: 8,
    name: "Arlovey Romance Hoodie",
    price: 949,
    badge: "Romantic Drop!",
    category: "Hoodies",
    garmentType: "Long Sleeve Hoodie Sweatshirt with front pocket",
    description: "Dreamy anime couple vibes in cozy beige — perfect for romance lovers and those who believe in forever moments.",
    longDescription: "Soft beige hoodie with a dreamy anime couple print. Perfect for gifting to your person or wearing as a solo romantic. Thick, cozy fabric with hand-printed artwork that tells a love story.",
    images: ["/images/Hoodie.jpg"],
    instagramUrl: "https://www.instagram.com/p/DRpIZoADHN3/",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    care: "Machine wash gentle cold. Do not bleach. Dry in shade."
  },
  {
    id: 9,
    name: "Dino Couple Hoodies",
    price: 1759,
    badge: "Matching Set!",
    category: "Hoodies",
    garmentType: "Long Sleeve Hoodie Sweatshirt with front pocket",
    description: "Matching hoodies with adorable skateboarding dinos! 'The Yapper' & 'The Listener' — perfect for besties or couples.",
    longDescription: "A matching set for the duo that balances each other out. 'The Yapper' and 'The Listener' — two skateboarding dinos hand-printed on cozy hoodies. Price is for the pair. Perfect couple gift or bestie set.",
    images: ["/images/CoupleHoodie_1.jpg", "/images/CoupleHoodie_2.jpg", "/images/CoupleHoodie_3.jpg", "/images/CoupleHoodie_4.jpg"],
    instagramUrl: "https://www.instagram.com/reel/DRHpD3nDD0Z/",
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    note: "Price is for the matching pair",
    care: "Machine wash gentle cold. Do not bleach. Dry in shade."
  }
];
